---
title: "Brownlows Bets"
author: "Put your name here!"
date: "put the date here"
output: html_document
---

<!-- We recommend you use git branches -- create a separate branch for each major section i.e. Introduction, Methods, Results, Inferential Results, and Discussion and Conclusions - leave the YAML block untouched until the final merge where you put in your own name !-->

# Introduction

<!--In this section you explain what you are trying to show.  Where did the data come from?  What is the research or other question you are trying to answer?!-->

 At the first day of class there are 35 students in Math Statistics class and professor Brownlow always proposes this bet to his students "I will wager $2 to your bet of $1 that at least two people in today's class have  the same birthday.  He tells me he has made that bet 1137 times so far. Where do you think his profits are? Discuss this in a markdown document

# Methods

<!--Decide on your methods:  In this section explain the approach you will take to attack the issue --- how will you decide on a likely estimate of professor Brownlow's earnings or losses after 1137 bets. Also explain how you construct a 95% confidence interval about your estimate of his winnings !-->

In order to calculate an estimate of Professor Brownlow's earnings, we need to create a simulation of the total wagers Professor Brownlow claims to have made. First, we will make a test class of 35 students and compare their birthdays. We create a sample of 365 possible birthdays, extract a random 35 of them (1 birthday per student), and check if any of those birthdays are the same. We then repeat this test 1137 times to match the amount of times Professor Brownlow made the bet. From each test, if any birthdays are duplicated, we add 1 dollar to Brownlow's earnings; if there are no duplicated birthdays, we deduct 2 dollars from Brownlow's earnings. In order to make a more accurate prediction, we will repeat our set of 1137 wagers 100 times and save the resultant earnings in an array.  

From the stored earnings, we can calculate the mean profit to get an idea of how much money Brownlow might have earned after making this bet 1137 times. In order to construct a 95% confidence interval, we will examine the imperical data from our array of profits, and apply the standard deviation to the mean. Going two standard deviations below the mean and two standard deviations above the mean will give the required confidence interval.

#Profit Estimate

<!--Explain and display the results of your method of coming up with the estimate of professor Brownlows betting!-->


# Confidence interval of Brownlows earning

<!--Explain and display your method of coming up with a 95% confidence interval of  professor Brownlows-->


# Discussion and Conclusion

<!--Discussion and conclusion here.  If professor Brownlow is consistantly making or losing money how could he change his payout so that his profits center on zero?  Also discuss what size his class should be in order to have his current scheme balance at zero profit.!-->

